### ISSUE TITLE
W3C annotations and activity stream documents

### ISSUE THREAD

**Issue by mustafayildiz2** [bounswe574-G3/bounswe574-2022#11]
Each group member will reread the W3C annotations and activity stream documents.

**Comment by mustafayildiz2** [comment]
Some videos and articles on the subject have been examined.

**Comment by SametTasti** [comment]
Still reading.

**Comment by mustafayildiz2** [comment]
Resources
1) Hypothesis, annotation python libraries

- [](https://web.hypothes.is/tools-plug-ins-and-integrations)
- [](https://github.com/judell/Hypothesis)
- [](https://github.com/kshaffer/pypothesis)

2)Articles

- [](https://medium.com/@atakanguney94/the-standardization-of-annotations-3c9a5115f5fe)


3) Videos

- [](https://www.youtube.com/watch?v=rj_mCLOLOCw)
- [](https://www.youtube.com/watch?v=87h0nYi-i9o)
- [](https://www.youtube.com/watch?v=YE4BYKvPQrs)
- [](https://www.youtube.com/watch?v=bR0TxJV6Cpc)

4) Working Groups

- [](https://web.hypothes.is/)
- [](https://annotator.apache.org/)
- [](http://annotatorjs.org/)

**Comment by SametTasti** [comment]
Moved [here](https://github.com/bounswe574-G3/bounswe574-2022/wiki/Research-on-Activity-Stream-and-Web-Annotation-Data-Model#various-links-and-resources) for ease of access.
