### ISSUE TITLE
Mock-ups for user badges

### ISSUE THREAD

**Issue by mustafayildiz2** [bounswe574-G3/bounswe574-2022#15]
In order to clarify the requirements and functionality of additional improvements, mock-ups for user badges will be prepared

**Comment by boraysr** [comment]
Mockup of a basic conversation between two members of a learning space and the intended use of the badges in their avatars is added to the wiki

**Comment by SametTasti** [comment]
The link is [here](https://github.com/bounswe574-G3/bounswe574-2022/wiki/MockUps#mockup-for-badges-on-avatars).
