### ISSUE TITLE
Each group member shall download the last semester's project from repo and run it locally.

### ISSUE THREAD

**Issue by mustafayildiz2** [bounswe574-G3/bounswe574-2022#17]
Each group member will add a screenshot from the project.

**Comment by mustafayildiz2** [comment]
An example screenshot about a co-learnign space with its learnign steps and discussion board.
![CoLearninSpace](https://user-images.githubusercontent.com/103500947/198954760-5038635b-9f80-47e2-addc-68082410171c.png)

**Comment by AydosIlgazi** [comment]
Example screenshot of created learning space
<img width="1391" alt="Screen Shot 2022-11-06 at 22 06 06" src="https://user-images.githubusercontent.com/32308526/200190121-dbdbc8a4-8196-4b57-a61c-f505b25299e6.png">

**Comment by SametTasti** [comment]
![working_system](https://user-images.githubusercontent.com/115422731/200308569-71b93271-4fcf-4c91-b42b-861f6d7e3958.PNG)
Screenshot of the system working.
