### ISSUE TITLE
W3C Activity Stream, W3C Web Annotation Data Model and Wikidata Research 

### ISSUE THREAD

**Issue by erdembilgin** [bounswe574-G3/bounswe574-2022#3]
Studying the recommended specifications for W3C Activity Stream (https://www.w3.org/TR/activitystreams-core/), W3C Web Annotation Data Model (https://www.w3.org/TR/annotation-model/), and Wikidata (https://www.wikidata.
org). Creating a page to document the research.

**Comment by erdembilgin** [comment]
Research is completed and document is added to the [wiki](https://github.com/bounswe574-G3/bounswe574-2022/wiki/Research-on-Activity-Stream-and-Web-Annotation-Data-Mode) page

**Comment by mustafayildiz2** [comment]
Research on  W3C Activity Stream and W3C Web Annotation Data Model was completed.
[https://github.com/bounswe574-G3/bounswe574-2022/wiki/Research-on-Activity-Stream-and-Web-Annotation-Data-Mode](url)
